"""add extracted_text to documents and page_number to document_chunks

Revision ID: 4df49f609e8e
Revises: 7cfbab6f4a5d
Create Date: 2026-08-12 13:59:24.971825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df49f609e8e'
down_revision: Union[str, Sequence[str], None] = '7cfbab6f4a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'extracted_text')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
