"""add original filename to documents

Revision ID: 7cfbab6f4a5d
Revises: 268e281c4add
Create Date: 2026-08-11 16:29:42.855910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfbab6f4a5d'
down_revision: Union[str, Sequence[str], None] = '268e281c4add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'original_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
